# unit2_demo_tests.py
# Runs required test cases

from unit2_linear_ds import DynamicArray, SinglyLinkedList, Stack, Queue, is_balanced

print("=== T1. DynamicArray ===")
arr = DynamicArray()
for i in range(1, 6):
    arr.append(i)
    print(f"Appended {i}: size={arr.size()}, capacity={arr.capacity()}")
print("Array:", arr)
arr.pop()
arr.pop()
print("After 2 pops:", arr)
arr.insert(1, 99)
arr.delete(2)
print("After insert/delete:", arr)

print("\n=== T2. Singly Linked List ===")
sll = SinglyLinkedList()
sll.insert_at_beginning(3)
sll.insert_at_beginning(2)
sll.insert_at_beginning(1)
sll.insert_at_end(4)
sll.insert_at_end(5)
print("Traverse:", sll.traverse())
sll.delete_by_value(3)
print("After deleting 3:", sll.traverse())
print("Search 4:", sll.search(4))
print("Search 100:", sll.search(100))

print("\n=== T3. Stack ===")
stack = Stack()
stack.push(10)
stack.push(20)
stack.push(30)
print("Peek:", stack.peek())
print("Pop:", stack.pop())
print("Pop:", stack.pop())
print("Peek after pops:", stack.peek())

print("\n=== T4. Queue ===")
queue = Queue()
queue.enqueue(7)
queue.enqueue(8)
queue.enqueue(9)
print("Front:", queue.front())
print("Dequeue:", queue.dequeue())
print("Dequeue:", queue.dequeue())
print("Front after dequeues:", queue.front())

print("\n=== T5. Parentheses Checker ===")
print("([]):", is_balanced("([])"))
print("([)]:", is_balanced("([)]"))
print("(((:", is_balanced("((("))
print("Empty string:", is_balanced(""))